### ISSUE TITLE
Need help in evaluating my model

### ISSUE THREAD

**Issue by prasadpande1990** [raj2014/Walmart_TripType_Classification#1]
Hi Raj,

First thank you for putting your competition code with detailed description for beginners learning. 

I am working on the same Walmart Dataset for learning purpose and closely referring to your code to understand its working.

I wanted to know is there a way I can evaluate the mlogloss on the test dataset in R since there is no label present in the test data. 
Currently I am using xgb.cv() method to get the test mlogloss on n-fold cross validation but that is limited to train data. Can we apply similar method on test data.

Thanks,
Prasad

**Comment by raj2014** [comment]
Hi Prasad,

Labels for the test set are not shared to the participants even after the completion of the competition.
You are allowed to make submissions even after competition completion  to check how you end up on the private LB which inturn indirectly gives you the mlogloss on the testset from Kaggle .

I think it is the only way you can assess your model on the testset.

Hope it helps!,my scripts takes around 3+ hrs for cv !

Thanks,
Raj Jetty

**Comment by prasadpande1990** [comment]
Thank you
